name: tot
channels:
  - anaconda
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.9.18
  - pip:
    - anytree==2.12.1
    - numpy==1.26.4
    - openai==1.12.0
    - pandas==2.2.0
    - peft==0.9.0
    - py-dot==0.6.5
    - pyarrow==15.0.0
    - pyarrow-hotfix==0.6
    - pydantic==2.6.1
    - pydantic-core==2.16.2
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.31.0
    - responses==0.18.0
    - rich==13.7.1
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - shtab==1.7.1
    - six==1.16.0
    - sniffio==1.3.0
    - sympy==1.12
    - threadpoolctl==3.3.0
    - tiktoken==0.6.0
    - tokencost==0.1.7
    - tokenizers==0.15.2
    - torch==2.2.0
    - tqdm==4.66.2
    - transformers==4.38.0
    - triton==2.2.0
    - trl==0.7.11
    - typing-extensions==4.9.0
    - tyro==0.7.3
    - tzdata==2024.1
    - urllib3==2.2.1
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.17.0
