data: # Dataset configurations
  tree_path: ./outputs/asap_6_validation_gpt-42_0506-0546.jsonl # Source tree data file from the stage 1
  path: ./data/datasets/ # Path for the original dataset
  name: asap_6 # subset name
  input_column: Response # input data column (student answer)
  label_column: Mark # target column (score)
  saving_path: ./outputs/generation_result/ # generated query saving path

log: # log configuration
  path: ./outputs/logs/generation.log
  enable: True
