data: # Dataset configurations
  path: ./data/datasets/ # Path for the original dataset
  name: asap_6 # subset name
  split: test # dataset split
  input_column: Response # input data column (student answer)
  label_column: Mark # target column (score)
  saving_path: ./outputs/query_result/ # generated trees saving path

log: # log configuration
  path: ./outputs/logs/tot_query.log # log path
  enable: True # enable log or not

llm: # llm configurations
  model: open-mixtral-8x7b # llm name, we support vllm api, openai api, mistral api, and huggingface models
  tempreture: 0.7 # query tempreture
  candidates: 10 # outputs for each query 

prompt: # prompt configuration
  system: False # add system prompt
  shot_mode: few-shot # provide few-shot examples
  history: wo_demo_history # prompt mode
  order: default # order configuration
  sum_score: by_llm # score summary method
  saving_path: ./outputs/graphs # path to save trees
  save_tree: True # save tree or not
  save_tree_threshold: 2 # min threshold for saving tree, 2 means two identical paths

